"""Persistence adapters for episodic and semantic memory and durable storage."""

from __future__ import annotations

from .autonomy_store import (
    AutonomyNotFoundError,
    AutonomyStore,
    AutonomyStoreError,
)
from .file_session_repo import (
    CheckpointError,
    FileSessionRepository,
)
from .memory import (
    CORE_MEMORY_FILE,
    EpisodeNotFoundError,
    EpisodeRecord,
    EpisodeStatus,
    EpisodeStore,
    EpisodeStoreError,
    FileCoreMemoryStore,
    FileFactRepository,
    MEMORY_INDEX,
    create_memory,
    delete_memory,
    dump_frontmatter,
    ensure_memory_dir,
    entrypoint_path,
    episode_from_session,
    format_episode_manifest,
    format_manifest,
    get_memory,
    memory_dir,
    normalize_memory_id,
    parse_frontmatter,
    read_entrypoint,
    read_episodes_for_surfacing,
    read_memories_for_surfacing,
    rebuild_index,
    scan_memory_files,
    search_memories,
    slugify,
    update_memory,
    write_memory_file,
)

__all__ = [
    "AutonomyNotFoundError",
    "AutonomyStore",
    "AutonomyStoreError",
    "CORE_MEMORY_FILE",
    "CheckpointError",
    "EpisodeNotFoundError",
    "EpisodeRecord",
    "EpisodeStatus",
    "EpisodeStore",
    "EpisodeStoreError",
    "FileCoreMemoryStore",
    "FileFactRepository",
    "FileSessionRepository",
    "MEMORY_INDEX",
    "create_memory",
    "delete_memory",
    "dump_frontmatter",
    "ensure_memory_dir",
    "entrypoint_path",
    "episode_from_session",
    "format_episode_manifest",
    "format_manifest",
    "get_memory",
    "memory_dir",
    "normalize_memory_id",
    "parse_frontmatter",
    "read_entrypoint",
    "read_episodes_for_surfacing",
    "rebuild_index",
    "scan_memory_files",
    "search_memories",
    "slugify",
    "update_memory",
    "write_memory_file",
]
