"""Backward-compatibility facade for Fact repository & store (migrated to .memory.fact)."""

from __future__ import annotations

from .memory.fact import (
    FRONTMATTER_MAX_LINES,
    FileFactRepository,
    MAX_INDEX_BYTES,
    MAX_INDEX_LINES,
    MAX_MEMORY_CHARS,
    MAX_MEMORY_CONTENT_CHARS,
    MAX_MEMORY_DESCRIPTION_CHARS,
    MAX_MEMORY_FILES,
    MAX_MEMORY_NAME_CHARS,
    MemoryStoreError,
    create_memory,
    delete_memory,
    dump_frontmatter,
    format_manifest,
    get_memory,
    normalize_memory_id,
    parse_frontmatter,
    read_entrypoint,
    read_memories_for_surfacing,
    rebuild_index,
    scan_memory_files,
    search_memories,
    slugify,
    update_memory,
    write_memory_file,
)

__all__ = [
    "FRONTMATTER_MAX_LINES",
    "FileFactRepository",
    "MAX_INDEX_BYTES",
    "MAX_INDEX_LINES",
    "MAX_MEMORY_CHARS",
    "MAX_MEMORY_CONTENT_CHARS",
    "MAX_MEMORY_DESCRIPTION_CHARS",
    "MAX_MEMORY_FILES",
    "MAX_MEMORY_NAME_CHARS",
    "MemoryStoreError",
    "create_memory",
    "delete_memory",
    "dump_frontmatter",
    "format_manifest",
    "get_memory",
    "normalize_memory_id",
    "parse_frontmatter",
    "read_entrypoint",
    "read_memories_for_surfacing",
    "rebuild_index",
    "scan_memory_files",
    "search_memories",
    "slugify",
    "update_memory",
    "write_memory_file",
]
