"""Approval facts are generated by policy, without authorizing new effects."""

import pytest

from wright.domain.model.tool import ToolCall
from wright.domain.policy.permission.resolver import PermissionResolver
from wright.domain.policy.permission.scope import AccessScope
from wright.domain.policy.permission.types import InvocationIdentity
from wright.infrastructure.runtime import LocalExecutionBackend
from wright.infrastructure.tools.command import execute_command_tool
from wright.infrastructure.tools.file import write_file_tool


def test_web_permission_fixtures_match_the_current_backend():
    import json
    from pathlib import Path

    from scripts.generate_permission_fixtures import (
        permission_copy,
        permission_fixtures,
    )

    path = Path(__file__).resolve().parents[2] / "web/tests/fixtures/permission-contract.json"
    assert json.loads(path.read_text(encoding="utf-8")) == permission_fixtures()
    copy_path = path.parents[2] / "src/permission-copy.json"
    assert json.loads(copy_path.read_text(encoding="utf-8")) == permission_copy()


@pytest.mark.parametrize(("command", "level", "flag"), [
    ("echo hello", "review", "executes_shell"),
    ("git status", "review", "executes_shell"),
    ("rm file", "elevated", "deletes_files"),
    ("Remove-Item file", "elevated", "deletes_files"),
    ("git reset --hard", "elevated", "modifies_git_state"),
])
def test_shell_risk_is_advisory_and_all_commands_still_require_approval(tmp_path, command, level, flag):
    result = PermissionResolver().resolve(ToolCall("execute_command", {"command": command}, "call"), execute_command_tool,
        backend=LocalExecutionBackend(tmp_path, lambda: tmp_path), scope=AccessScope(tmp_path), identity=InvocationIdentity("test"))
    assert result.decision == "deny" and result.source == "no_interaction"
    assert result.prompt.risk_level == level
    assert flag in result.prompt.risk_flags
    assert "may_delete_files" not in result.prompt.risk_flags
    assert result.prompt.to_dict()["risk_level"] == level


@pytest.mark.parametrize("content", ["hello", "x" * 1000])
def test_file_preview_is_separate_from_target_and_reports_truncation(tmp_path, content):
    path = tmp_path / "a.txt"
    result = PermissionResolver().resolve(ToolCall("write_file", {"file": str(path), "content": content}, "call"), write_file_tool,
        backend=LocalExecutionBackend(tmp_path, lambda: tmp_path), scope=AccessScope(tmp_path), identity=InvocationIdentity("test"))
    prompt = result.prompt
    assert prompt.targets == (str(path),)
    assert dict(prompt.summary_params)["targets"] == str(path)
    assert prompt.command == ""
    assert prompt.preview == content[:800]
    assert prompt.preview_truncated is (len(content) > 800)
    assert next(choice for choice in prompt.choices if choice.id == "allow_project_rule").resource["tool_name"] == "*"
    assert not path.exists()
