"""Renderer that records nothing. Tests and batch hosts use it."""

from __future__ import annotations

from .contracts import Renderer


class SilentRenderer(Renderer):
    """静默渲染器：什么都不输出。用于测试或批量任务。"""

    def on_reasoning_delta(self, piece: str) -> None: ...
    def on_content_delta(self, piece: str) -> None: ...
    def on_tool_call(self, tool_call) -> None: ...
    def on_tool_result(self, tool_call, tool_result) -> None: ...
    def on_final(self, answer) -> None: ...
